let myKey = "https//api.nytimes.com/svc/topstories/v2/science.json?api-key=0hGoPGeduATqFtOZvZb587v8yQsnU7yh";

let sections = [
        - "arts"
        - "automobiles"
        - "books"
        - "business"
        - "fashion"
        - "food"
        - "health"
        - "home"
        - "insider"
        - "magazine"
        - "movies"
        - "national"
        - "nyregion"
        - "obituaries"
        - "opinion"
        - "politics"
        - "realestate"
        - "science"
        - "sports"
        - "sundayreview"
        - "technology"
        - "theater"
        - "tmagazine"
        - "travel"
        - "upshot"
        - "world"
];